# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "usbhid" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ "${config.boot.kernelPackages.broadcom_sta}" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/497bb67d-0cdd-410c-9531-035545f2f7b0";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = 4;
}
